
name: 'banking_dwh'
version: '1.0.0'

\profile: 'banking_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"



models:
  banking_dwh:
    stg:
      +materialized: view
    sor:
      +materialized: table
      +tag: ["sor", "dbt_sor"]
    example:
      +materialized: view

tests:
  banking_dwh:
    sor:
      +store_failure: true
      +schema: test_failure