executor: "KubernetesExecutor"
redis:
  enabled: false

postgresql:
  image:
    # Chỉ định máy chủ lưu trữ là Docker Hub (mặc định)
    registry: docker.io 
    # chuyển sang dùng 'bitnamilegacy'
    repository: bitnamilegacy/postgresql 


images:
  airflow:
    repository: my-airflow-dbt
    tag: "1.0"
    pullPolicy: Never

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: "https://github.com/ndmanh2005/bank_dwh.git"
    branch: "main"
    subPath: ""
    wait: 60

logs:
  persistence:
    enabled: true
    size: 1Gi