images:
  airflow:
    repository: my-airflow-dbt
    tag: "1.0"
    pullPolicy: Never 

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: false

postgresql:
  image:
    tag: "16.4.0-debian-12-r5"