version: 2

sources:
  - name: stg
    schema: stg
    tables:
      - name: stg_branch
      - name: stg_customer
      - name: stg_account
      - name: stg_product
      - name: stg_transaction
      - name: stg_exchange_rate
      - name: stg_account_balance
